apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: phrr9c7p1-python
  janus-idp.io/tekton: phrr9c7p1-python
  backstage.io/kubernetes-id: phrr9c7p1-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: phrr9c7p1-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
